business/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.urls import include
from django.contrib.auth import views as authViews
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from apps.mainpage.views import mainPage,online
from apps.corporate.views import corporate
from apps.userform.views import careers, contacts
from apps.item.views import services
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', mainPage, name='mainPage'),
    path(_('hizmetler/<slug:slug>'), services, name='services'),
    path(_('kurumsal/'), corporate, name='corporate'),
    path(_('kariyer/'), careers, name='careers'),
    path(_('iletisim/'), contacts, name='contacts'),
    path(_('online/'), online, name='online'),
    path(_('rosetta/'), include('rosetta.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_URL) + static(settings.MEDIA_URL,
                                                                                          document_root=settings.MEDIA_ROOT)

apps/corporate/models.py
from django.db import models
from ..common.oneTextField import OneTextField
from ..common.mixins import AuditMixin
import os
from os.path import splitext
import uuid
from django.contrib.auth.models import User, Group
from translations.models import Translatable


def photo_path(instance, filename):
    # Save original file name in model
    instance.original_file_name = filename

    # Get new file name/upload path
    base, ext = splitext(filename)
    newname = "%s%s" % (uuid.uuid4(), ext)
    return os.path.join('images', newname)


class kurumsalKonum(OneTextField):
    class Meta:
        verbose_name = 'Kurumsal Konum'
        verbose_name_plural = 'Kurumsal Konumlar'
        default_permissions = ()
        permissions = (('liste', 'Listeleme Yetkisi'),
                       ('sil', 'Silme Yetkisi'),
                       ('ekle', 'Ekleme Yetkisi'),
                       ('guncelle', 'Güncelleme Yetkisi')
                       )


class kurumsalDetay(Translatable):
    tip = models.ForeignKey(kurumsalKonum, on_delete=models.DO_NOTHING, verbose_name='Konum')
    baslik = models.CharField(max_length=150, verbose_name="Başlık")
    icerik = models.TextField(default="", null=True, blank=True, verbose_name="İçerik")

    class TranslatableMeta:
        fields = ['baslik', 'icerik']


    def __str__(self):
        return self.baslik

    class Meta:
        verbose_name = 'Kurumsal'
        verbose_name_plural = 'Kurumsal'
        default_permissions = ()
        permissions = (('liste', 'Listeleme Yetkisi'),
                       ('sil', 'Silme Yetkisi'),
                       ('ekle', 'Ekleme Yetkisi'),
                       ('guncelle', 'Güncelleme Yetkisi')
                       )

apps/userform/models.py
from django.db import models
from ..common.mixins import AuditMixin,TimeStampMixin
from django.utils.translation import gettext_lazy as _
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.id, filename)

class Kariyer(AuditMixin):
    ad = models.CharField(max_length=200, null=True, verbose_name=_('Ad'))
    soyAd = models.CharField(max_length=200, null=True, verbose_name=_('Soyad'))
    ePosta = models.CharField(max_length=200, null=True, verbose_name=_('E-Posta'))
    adres = models.TextField(null=True, verbose_name=_('Adres'))
    telefon = models.CharField(max_length=200, null=True, verbose_name=_('Telefon'))
    cv = models.FileField(upload_to=user_directory_path, null=True, verbose_name=_('Özgeçmiş'))
    mesaj = models.TextField(null=True, verbose_name=_('Mesaj'))

    class Meta:
        verbose_name = _('Kariyer')
        verbose_name_plural = _('Kariyer')
        default_permissions = ()
        permissions = ((_('liste'), _('Listeleme Yetkisi')),
                       (_('sil'), _('Silme Yetkisi')),
                       (_('ekle'), _('Ekleme Yetkisi')),
                       (_('guncelle'), _('Güncelleme Yetkisi'))
                       )


class Iletisim(AuditMixin):
    ad = models.CharField(max_length=200, null=True, verbose_name=_('Ad'))
    soyAd = models.CharField(max_length=200, null=True, verbose_name=_('Soyad'))
    ePosta = models.CharField(max_length=200, null=True, verbose_name=_('E-Posta'))
    telefon = models.CharField(max_length=200, null=True, verbose_name=_('Telefon'))
    mesaj = models.TextField(null=True, verbose_name=_('Mesaj'))

    class Meta:
        verbose_name = _('İletişim')
        verbose_name_plural = _('İletişim')
        default_permissions = ()
        permissions = ((_('liste'), _('Listeleme Yetkisi')),
                       (_('sil'), _('Silme Yetkisi')),
                       (_('ekle'), _('Ekleme Yetkisi')),
                       (_('guncelle'), _('Güncelleme Yetkisi'))
                       )

apps/corporate/views.py
from django.shortcuts import render
from ..corporate.models import kurumsalDetay
# Create your views here.
def corporate(request):
    kurumsal=kurumsalDetay.objects.all().translate(request.LANGUAGE_CODE)
    return render(request, "corporate.html")

frontend/templates/careers.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}

{% endblock extra_css %}
{% block content %}

    <section class="hero-block">
        <picture>
            <source srcset="{% static 'img/kariyerBig.jpg' %}" media="(min-width: 992px)"/>
            <img class="img--bg" src="{% static 'img/kariyerBig.jpg' %}" alt="img"/>
        </picture>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="align-container">
                        <div class="align-container__item"><span
                                class="hero-block__overlay">{% trans "GFT Logistics" %}</span>
                            <h1 class="hero-block__title">{% trans "Kariyer" %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- section end-->

    <!-- section start-->
    <section class="section action-section pb-0 bottom-60">
        <div class="action-section__bg" style="height: 491px"><img class="img--bg"
                                                                   src="{% static 'img/kariyer.jpg' %}"
                                                                   alt="img"/>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="heading bottom-40">
                        <h3 class="heading__title">{% trans "Herkesin bir yolu, bir hikayesi vardır." %}
                            <br/>{% trans "Senin hikayeni birlikte yazalım." %}</h3>
                    </div>
                </div>

                <div class="col-lg-8 is--bordered" style="background: white">
                    <form method="post" enctype="multipart/form-data" class="mt-3">
                        {% csrf_token %}
                        <div class="row">


                            <div class="col-6">

                                <label for="id_ad" style="color: #ee2737">Ad:</label> <input type="text" name="ad"
                                                                                             maxlength="200"
                                                                                             class="form__field"
                                                                                             required="" id="id_ad">

                            </div>
                            <div class="col-6"><label for="id_soyAd" style="color: #ee2737">Soyad:</label> <input
                                    type="text" name="soyAd"
                                    maxlength="200"
                                    class="form__field"
                                    required=""
                                    id="id_soyAd"></div>
                            <div class="col-6"><label for="id_ePosta" style="color: #ee2737">E-Posta:</label> <input
                                    type="text"
                                    name="ePosta"
                                    maxlength="200"
                                    class="form__field"
                                    required=""
                                    id="id_ePosta"></div>
                            <div class="col-6"><label for="id_adres" style="color: #ee2737">Adres:</label> <textarea
                                    name="adres" cols="40"
                                    rows="10"
                                    class="form__field"
                                    required=""
                                    id="id_adres"></textarea>
                            </div>
                            <div class="col-6"><label for="id_telefon" style="color: #ee2737">Telefon:</label>
                                <input type="text"
                                       name="telefon"
                                       maxlength="200"
                                       class="form__field"
                                       required=""
                                       id="id_telefon">
                            </div>
                            <div class="col-6"><label for="id_cv" style="color: #ee2737">Özgeçmiş:</label> <input
                                    type="file" name="cv"
                                    class="form__field"
                                    required="" id="id_cv">
                            </div>
                            <div class="col-6"><label for="id_mesaj" style="color: #ee2737">Mesaj:</label> <textarea
                                    name="mesaj" cols="40"
                                    rows="10"
                                    class="form__field"
                                    required=""
                                    id="id_mesaj"></textarea>
                            </div>
                            <div class="col-6"><br>
                                <button type="submit" class="button button--green">
                                    <span>Gönder</span>
                                    <svg class="icon">
                                        <use xlink:href="#arrow"></use>
                                    </svg>
                                </button>
                            </div>


                    </form>


                </div>
            </div>


        </div>

        </div>
    </section>

{% endblock content %}
{% block extra_script %}


{% endblock extra_script %}

frontend/templates/corporate.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}

{% endblock extra_css %}
{% block content %}
    <!-- header end-->
    <main class="main">
        <!-- section start-->
        <section class="hero-block">
            <picture>
                <source srcset="{% static 'img/kurumsalBig.jpg' %}" media="(min-width: 992px)"/>
                <img class="img--bg" src="{% static 'img/kurumsalBig.jpg' %}" alt="img"/>
            </picture>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="align-container">
                            <div class="align-container__item"><span
                                    class="hero-block__overlay">{% trans "GFT Logistics" %}</span>
                                <h1 class="hero-block__title">{% trans "Kurumsal" %}</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->
        <!-- section start-->
        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-xl-5"><img class="w-100 bottom-50" src="{% static 'img/section_2.jpg' %}"
                                                        alt="img"/>
                        <div class="img-badge  " style="background-color: #ee2737"><img class="img-badge__img"
                                                                                        src="{% static 'img/badge-img.png' %}"
                                                                                        alt="img"/>
                            <h3 class="img-badge__title bottom-0">{% trans "Dünya Çapında " %}
                                <br/>{% trans "Acente Ağı" %}</h3>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-6 offset-xl-1">
                        <div class="heading bottom-20"><span class="heading__pre-title">{% trans "Hakkımızda" %} </span>
                            <h3 class="heading__title">{% trans "Ticaretin merkezi " %} <span
                                    class="color--green">{% trans "İstanbul" %}</span> {% trans "’da kurulduk" %}</h3>
                        </div>
                        <p>{% blocktranslate %}Onlarca yılın getirmiş olduğu deneyimimiz, sektöre olan tutkumuz ve
                            yenilikçi yaklaşım tarzımız ile kurulduğumuz günden itibaren portföyümüzdeki firmalara
                            hizmet sağlamaktan mutluluk duyuyoruz. {% endblocktranslate %}</p>
                        <p>{% blocktranslate %}Deneyimli kadromuz ve dünya çapında acente ağlarımızla kara, deniz, hava
                            ve demiryolu taşımacılığında sınırları aşan hizmetler
                            veriyoruz.  {% endblocktranslate %}</p>
                        <p>{% blocktranslate %}Ekonominin lokomotif unsurlarından olan ithalat ve ihracat yapan firmalar
                            için ürün tedarik süreçlerini ve depolama hizmetlerini de kapsayan katma değerli çözümler
                            sunuyoruz.  {% endblocktranslate %}</p>
                        <p>{% blocktranslate %}Geniş coğrafi erişim sağlayan dünya çapındaki acente ağımızla,  operasyon
                            gücümüzü daima artırıyoruz.  {% endblocktranslate %}</p>
                        <p>{% blocktranslate %}Üstlendiğimiz hayati bağlantı görevinin müşterilerimize daha fazla değer
                            katabilmesi için becerilerimizi daima geliştiriyoruz.  {% endblocktranslate %}</p>
                        <p>{% blocktranslate %}Özelleştirilmiş üst düzey hizmetlerimizle müşterilerimizin işlerine değer
                            katan ve onların güvenini kazanan bir çözüm sağlayıcı olmaktan gurur
                            duyuyoruz.  {% endblocktranslate %}</p>

                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->
        <!-- section start-->
        <section class="section pt-0">
            <div class="container">
                <div class="row flex-column-reverse flex-lg-row">
                    <div class="col-lg-6 top-50 top-lg-0">
                        <div class="heading bottom-20">
                            <h3 class="heading__title">  {% trans "Vizyon" %}  </h3>
                        </div>
                        <p class="bottom-0">{% blocktranslate %}‘Sektöre Değer Kat, Sınırları Aş’ mottomuz;
                            müşterilerimizden ve acentelerimizden aldığımız güç ile lojistik ve dış ticaret ekosistemi
                            içerisinde sürdürülebilir başarıyı ve memnuniyeti sağlama konusunda taahhüdümüzün temelini
                            oluşturmaktadır.
                        {% endblocktranslate %}</p>
                        <p class="bottom-0 mt-2">{% blocktranslate %} Vizyonumuz, sürdürülebilir başarı ve memnuniyeti
                            yıldan yıla artırmaktır.
                        {% endblocktranslate %}</p>
                        <div class="heading bottom-20 mt-4">
                            <h3 class="heading__title">  {% trans "Misyon" %}  </h3>
                        </div>
                        <p class="bottom-0">{% blocktranslate %}Misyonumuz; sunduğumuz hızlı ve kaliteli çözümler ile
                            sadece lojistik hizmeti üreten değil, müşterilerimizin ticari çözüm ortağı olarak hareket
                            eden bir kurum olmak.    {% endblocktranslate %}</p>

                    </div>

                    <div class="col-lg-6 col-xl-5 offset-xl-1"><img class="w-100" src="{% static 'img/section_1.jpg' %}"
                                                                    alt="img"/></div>
                </div>
            </div>
        </section>
        <!-- section end-->
        <!-- section start-->
        <!-- section start-->
        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-12"><img src="{% static 'img/map-transx.png' %}" alt="img"/></div>
                </div>
                <div class="row offset-50">
                    <div class="col-md-6 col-lg-4 text-center">
                        <div class="counter counter--blue">
                            <div class="counter__top"><span
                                    class="js-counter counter__count">{% trans "8" %}</span><span
                                    class="counter__subject">{% trans "Özellik" %}</span></div>
                            <div class="counter__lower"><span
                                    class="counter__details">{% trans "Güçlü Operasyonlar İçin" %}</span></div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 text-center">
                        <div class="counter counter--blue">
                            <div class="counter__top"><span
                                    class="js-counter counter__count">{% trans "6" %}</span><span
                                    class="counter__subject">{% trans "Değer" %}</span></div>
                            <div class="counter__lower"><span
                                    class="counter__details">{% trans "En İyi Olmak İçin" %}</span></div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 text-center">
                        <div class="counter counter--blue">
                            <div class="counter__top"><span
                                    class="js-counter counter__count">{% trans "7" %}</span><span
                                    class="counter__subject">{% trans "Hizmet" %}</span></div>
                            <div class="counter__lower"><span
                                    class="counter__details">{% trans "Mutlu Müşteriler İçin" %}</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- section end-->


        <!-- section start-->
        <section class="section">
            <div class="container">
                <div class="row bottom-70">
                    <div class="col-12">
                        <div class="heading heading--center"><span class="heading__pre-title">{% trans "DEĞERLERİMİZ" %}</span>
                            <h3 class="heading__title">{% trans "DEĞERLERİMİZ" %}</h3>
                        </div>
                    </div>
                </div>
                <div class="row offset-50">
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                               <img src="{% static 'img/durustluk.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "Dürüstlük ve Güven" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Yaptığımız işe, birlikte çalıştığımız ekimize ve hizmet sunduğumuz müşterilerimize karşı olan dürüstlüğümüz organizasyon yapımızın temel unsurudur. Dünya çapında güven sağlamış güçlü acente ağımızla hareket etmenin sağladığı faydaya inanıyoruz. {% endblocktranslate %}</p>
                        </div>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                              <img src="{% static 'img/mukemmellik.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "Mükemmellik ve Kalite" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Özelleştirilmiş üst düzey hizmetlerimizde mükemmellik ve sürekli iyileştirmenin müşterilerimizin işlerine değer kattığına inanıyoruz. Süreç analizi, optimizasyon ve müşteri deneyimlerini baz alarak kaliteli hizmet anlayışımızı geliştiriyoruz.  {% endblocktranslate %}</p>
                        </div>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                                <img src="{% static 'img/musteri.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "Müşteri Odaklı Olma" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Lojistik, depolama ve ürün tedarikinde hizmet verdiğimiz müşterilerimizin ihtiyaçlarını tam olarak anlamak, müşterilerimiz için değer sağlamak ve onların taleplerine kaliteli ve hızlı cevap vermek önceliğimizdir. {% endblocktranslate %}</p>
                        </div>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                               <img src="{% static 'img/saygi.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "İnsana Saygı" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Yönetim ve hizmet anlayışımızın temelini insana saygı oluşturur. İletişimde şeffaf ve duyarlı davranırız. Her zaman değer verir ve can kulağıyla dinleriz. Açık fikirlilik, doğru iletişim ve saygı işimizden ayrı düşünülemez. {% endblocktranslate %}</p>
                        </div>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                                <img src="{% static 'img/sosyal.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "Sosyal Sorumluluk" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Çevreye, doğaya ve insana değer veren bir yaklaşımla hizmet sağlarız. Topluma ve çevremize karşı olan sorumluluğumuzun farkındayız. Daha iyi bir gelecek için daima katkı sunmaya çalışırız. {% endblocktranslate %}</p>
                        </div>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4 text-center">
                        <div class="icon-item">
                            <div class="icon-item__img">
                              <img src="{% static 'img/etik.png' %}" alt="icon"/>
                            </div>
                            <h6 class="icon-item__title bottom-0">{% trans "Etik Çalışma" %}</h6>
                            <p class="count-item__text">{% blocktranslate %}Faaliyet gösterdiğimiz her coğrafyanın, her ülkenin yasalarına istisnasız uyarız. Etik kurallara, dürüstlük ilkelerine ve kültürel değerlere saygı gösteririz. Her zaman toplumumuza, insanımıza ve müşterimize karşı sorumlu davranırız. {% endblocktranslate %}</p>
                        </div>
                    </div>


                </div>
            </div>
        </section>
        <!-- section end-->

    </main>
    <!-- footer start-->
{% endblock content %}
{% block extra_script %}


{% endblock extra_script %}

frontend/templates/online.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}

{% endblock extra_css %}
{% block content %}
    <!-- header end-->
    <main class="main">
   <!-- section start-->
        <section class="hero-block">
            <picture>
                <source srcset="{% static 'img/1920x657_Online.jpg' %}" media="(min-width: 992px)"/>
                <img class="img--bg" src="{% static 'img/1920x657_Online.jpg' %}" alt="img"/>
            </picture>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="align-container">
                            <div class="align-container__item"><span
                                    class="hero-block__overlay">{% trans "GFT Logistics" %}</span>
                                <h1 class="hero-block__title">{% trans "Online İşlemler" %}</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->
        <!-- section start-->
        <section class="section">
            <div class="container">
                <div class="row flex-column-reverse flex-lg-row">
                    <div class="col-lg-12">
                        <iframe id="frg-track" src="https://frigian.com/events/tracking-request.php?dm=gft&ln=tr"
                                width="100%" height="200" scrolling="no" frameBorder="0" style="overflow:hidden;"></iframe>
                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->
    </main>
    <!-- footer start-->
{% endblock content %}
{% block extra_script %}


{% endblock extra_script %}

frontend/templates/services.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}

{% endblock extra_css %}
{% block content %}
    <!-- header end-->
    <main class="main">
        <!-- section start-->
        <section class="hero-block">
            <picture>
                <source srcset="{{ hizmet.resim_url }}" media="(min-width: 992px)"/>
                <img class="img--bg" src="{{ hizmet.resim_url }}" alt="img"/>
            </picture>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="align-container">
                            <div class="align-container__item"><span
                                    class="hero-block__overlay">{% trans "GFT Logistics" %}</span>
                                <h1 class="hero-block__title">{{ hizmet }}</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->
        <!-- section start-->
        <section class="section service-details">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-xl-9"><img class="service-details__img"
                                                        src="{{ hizmet.resim1_url }}" alt="img"/>
                        <h4 class="service-details__title">{{ hizmet }}</h4>
                        <p>{{ hizmet.detay }}</p>
                        {% if hizmet.sunulanHizmet.all %}
                            <h4 class="service-details__title">{% trans "Sunulan Hizmetler" %}</h4>
                            <div class="row bottom-50 top-40">
                                {% for sunulan in hizmet.sunulanHizmet.all %}
                                    <div class="col-sm-6 col-md-5 col-xl-4">

                                        <ul class="list list--check list--reset">
                                            <li class="list__item">{{ sunulan }}</li>
                                        </ul>

                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% if hizmet.resim2 %}
                            <h4 class="service-details__title">{% trans "Üyeliklerimiz" %}</h4>
                            <div class="row bottom-50 top-40">

                                <div class="row align-items-end bottom-70">
                                    <div class="col-md-2">
                                        <div class="heading">
                                            <img
                                                 src="{{ hizmet.resim2_url }}" alt="img"/>
                                        </div>
                                    </div>
                                    <div class="col-md-10  ">
                                        <p class="bottom-0">     {{ hizmet.ekaciklama }}</p>
                                    </div>
                                </div>


                            </div>
                        {% endif %}
                    </div>
                    <div class="col-lg-4 col-xl-3 top-50 top-lg-0">
                        <div class="row">
                            <div class="col-md-6 col-lg-12 bottom-50">
                                <h5 class="service-details__subtitle">{% trans "Hizmetler" %}</h5>
                                <ul class="category-list list--reset">
                                    {% for hizmet1 in menuList %}
                                        {% if hizmet1 == hizmet %}
                                            <li class="category-list__item item--active"><a class="category-list__link"
                                                                                            href="{% url 'services' hizmet1.slug %}">{{ hizmet1 }}</a>
                                            </li>
                                        {% else %}
                                            <li class="category-list__item"><a class="category-list__link"
                                                                               href="{% url 'services' hizmet1.slug %}">{{ hizmet1 }}</a>
                                            </li>

                                        {% endif %}

                                    {% endfor %}
                                </ul>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- section end-->

    </main>
    <!-- footer start-->
{% endblock content %}
{% block extra_script %}


{% endblock extra_script %}